import type { Article, Video, Gallery } from "./types";

export const mockArticles: Article[] = [
  {
    id: 1,
    documentId: "a1",
    title: "All eyes on Pacaltsdorp for Eden Sports Awards",
    slug: "all-eyes-on-pacaltsdorp-for-eden-sports-awards",
    excerpt: "EDEN NEWS - The Eden Sports Awards tonight, 6 February, is set to honour excellence and commitment in the region's sporting community.",
    isTopStory: true,
    isBreaking: false,
    isFeatured: true,
    viewCount: 1250,
    publishedDate: "2026-02-06T14:00:00.000Z",
    section: "sport",
    createdAt: "2026-02-06T14:00:00.000Z",
    updatedAt: "2026-02-06T14:00:00.000Z",
    category: { id: 1, name: "Sport", slug: "sport", color: "#DC2626", parentSection: "sport" },
    author: { id: 1, name: "George Herald Reporter", slug: "george-herald-reporter", role: "Journalist" },
  },
  {
    id: 2,
    documentId: "a2",
    title: "Van Druten's bail hearing approaches: Tension builds at Plettenberg Bay court",
    slug: "van-druten-bail-hearing-approaches",
    excerpt: "GARDEN ROUTE NEWS - The tension is subdued at the Plettenberg Bay Magistrate's Court as those gathered wait for Bevan van Druten's fourth appearance.",
    isTopStory: true,
    isBreaking: true,
    isFeatured: false,
    viewCount: 3420,
    publishedDate: "2026-02-06T12:00:00.000Z",
    section: "crime",
    createdAt: "2026-02-06T12:00:00.000Z",
    updatedAt: "2026-02-06T12:00:00.000Z",
    category: { id: 2, name: "Crime", slug: "crime", color: "#DC2626", parentSection: "news" },
    author: { id: 1, name: "George Herald Reporter", slug: "george-herald-reporter", role: "Journalist" },
  },
  {
    id: 3,
    documentId: "a3",
    title: "Langkloof storm wreaks havoc",
    slug: "langkloof-storm-wreaks-havoc",
    excerpt: "GARDEN ROUTE NEWS AND VIDEOS - Strong storm winds wreaked havoc in the Langkloof area, leaving farmers, business owners and residents devastated.",
    isTopStory: true,
    isBreaking: false,
    isFeatured: false,
    viewCount: 2100,
    publishedDate: "2026-02-06T10:00:00.000Z",
    section: "local",
    createdAt: "2026-02-06T10:00:00.000Z",
    updatedAt: "2026-02-06T10:00:00.000Z",
    category: { id: 3, name: "Local News", slug: "local-news", color: "#DC2626", parentSection: "news" },
    author: { id: 1, name: "George Herald Reporter", slug: "george-herald-reporter", role: "Journalist" },
  },
  {
    id: 4,
    documentId: "a4",
    title: "Council approves request for drought disaster declaration",
    slug: "council-approves-request-for-drought-disaster-declaration",
    excerpt: "GEORGE NEWS - George is on the brink of being declared a drought disaster area after Council approved an application for local disaster classification.",
    isTopStory: true,
    isBreaking: false,
    isFeatured: false,
    viewCount: 1890,
    publishedDate: "2026-02-04T14:00:00.000Z",
    section: "local",
    createdAt: "2026-02-04T14:00:00.000Z",
    updatedAt: "2026-02-04T14:00:00.000Z",
    category: { id: 3, name: "Local News", slug: "local-news", color: "#DC2626", parentSection: "news" },
    author: { id: 2, name: "Kristy Gillian", slug: "kristy-gillian", role: "Senior Journalist" },
  },
  {
    id: 5,
    documentId: "a5",
    title: "GRDM responds to Good's deviation concerns",
    slug: "grdm-responds-to-goods-deviation-concerns",
    excerpt: "GEORGE NEWS - The Garden Route District Municipality has defended its use of procurement deviations after the Good Party raised concerns.",
    isTopStory: true,
    isBreaking: false,
    isFeatured: false,
    viewCount: 950,
    publishedDate: "2026-02-04T16:00:00.000Z",
    section: "local",
    createdAt: "2026-02-04T16:00:00.000Z",
    updatedAt: "2026-02-04T16:00:00.000Z",
    category: { id: 3, name: "Local News", slug: "local-news", color: "#DC2626", parentSection: "news" },
    author: { id: 1, name: "George Herald Reporter", slug: "george-herald-reporter", role: "Journalist" },
  },
  {
    id: 6,
    documentId: "a6",
    title: "Martin Ferreira trades waves for tarmac to fete Outeniqua Chair Challenge",
    slug: "martin-ferreira-trades-waves-for-tarmac",
    excerpt: "GEORGE NEWS - Participants in this year's Outeniqua Chair Challenge have been training and testing their racing wheels for the 22nd chapter of this well-loved event.",
    isTopStory: false,
    isBreaking: false,
    isFeatured: false,
    viewCount: 680,
    publishedDate: "2026-02-05T08:00:00.000Z",
    section: "sport",
    createdAt: "2026-02-05T08:00:00.000Z",
    updatedAt: "2026-02-05T08:00:00.000Z",
    category: { id: 1, name: "Sport", slug: "sport", color: "#DC2626", parentSection: "sport" },
    author: { id: 1, name: "George Herald Reporter", slug: "george-herald-reporter", role: "Journalist" },
  },
  {
    id: 7,
    documentId: "a7",
    title: "Structuring for scale: The role of offshore funds in global growth",
    slug: "structuring-for-scale-offshore-funds",
    excerpt: "BUSINESS NEWS - As investment strategies and investor bases become increasingly international, purely domestic fund structures can place South African investment managers at a disadvantage.",
    isTopStory: false,
    isBreaking: false,
    isFeatured: false,
    viewCount: 420,
    publishedDate: "2026-02-04T12:00:00.000Z",
    section: "business",
    createdAt: "2026-02-04T12:00:00.000Z",
    updatedAt: "2026-02-04T12:00:00.000Z",
    category: { id: 4, name: "Business", slug: "business", color: "#DC2626", parentSection: "news" },
    author: { id: 3, name: "Business Desk", slug: "business-desk", role: "Editor" },
  },
  {
    id: 8,
    documentId: "a8",
    title: "Why the right hydration is essential for South African children in summer",
    slug: "why-the-right-hydration-is-essential",
    excerpt: "LIFESTYLE NEWS - The hottest month of the year is upon us, which means increasing fluid intake. While many adults are conscious of this need, hydration remains underestimated for children.",
    isTopStory: false,
    isBreaking: false,
    isFeatured: false,
    viewCount: 750,
    publishedDate: "2026-02-04T10:00:00.000Z",
    section: "lifestyle",
    createdAt: "2026-02-04T10:00:00.000Z",
    updatedAt: "2026-02-04T10:00:00.000Z",
    category: { id: 5, name: "Lifestyle", slug: "lifestyle", color: "#DC2626", parentSection: "lifestyle" },
    author: { id: 1, name: "George Herald Reporter", slug: "george-herald-reporter", role: "Journalist" },
  },
  {
    id: 9,
    documentId: "a9",
    title: "South Africa is grateful to be included in AGOA for now",
    slug: "south-africa-grateful-agoa",
    excerpt: "BUSINESS NEWS - MISA, the Motor Industry Staff Association, welcomes South Africa's inclusion in the extension of AGOA as a positive development.",
    isTopStory: false,
    isBreaking: false,
    isFeatured: false,
    viewCount: 310,
    publishedDate: "2026-02-05T14:00:00.000Z",
    section: "business",
    createdAt: "2026-02-05T14:00:00.000Z",
    updatedAt: "2026-02-05T14:00:00.000Z",
    category: { id: 4, name: "Business", slug: "business", color: "#DC2626", parentSection: "news" },
    author: { id: 3, name: "Business Desk", slug: "business-desk", role: "Editor" },
  },
  {
    id: 10,
    documentId: "a10",
    title: "Proteas go down to India in worthwhile T20 World Cup warm-up",
    slug: "proteas-go-down-to-india-t20",
    excerpt: "CRICKET NEWS - The Proteas went down to India by 30 runs at the DY Patil Stadium in their only warm-up match ahead of the 2026 T20 World Cup.",
    isTopStory: false,
    isBreaking: false,
    isFeatured: false,
    viewCount: 890,
    publishedDate: "2026-02-05T14:00:00.000Z",
    section: "sport",
    createdAt: "2026-02-05T14:00:00.000Z",
    updatedAt: "2026-02-05T14:00:00.000Z",
    category: { id: 6, name: "Cricket", slug: "cricket", color: "#DC2626", parentSection: "sport" },
    author: { id: 4, name: "Sport Desk", slug: "sport-desk", role: "Sports Editor" },
  },
  {
    id: 11,
    documentId: "a11",
    title: "Freshly baked gluten-free rolls made in an air fryer",
    slug: "freshly-baked-gluten-free-rolls",
    excerpt: "LIFESTYLE NEWS - Homemade gluten-free rolls taste different from anything you buy in a packet. They have a tender crumb and a soft chew, making them perfect.",
    isTopStory: false,
    isBreaking: false,
    isFeatured: false,
    viewCount: 540,
    publishedDate: "2026-02-04T09:00:00.000Z",
    section: "lifestyle",
    createdAt: "2026-02-04T09:00:00.000Z",
    updatedAt: "2026-02-04T09:00:00.000Z",
    category: { id: 5, name: "Lifestyle", slug: "lifestyle", color: "#DC2626", parentSection: "lifestyle" },
    author: { id: 1, name: "George Herald Reporter", slug: "george-herald-reporter", role: "Journalist" },
  },
  {
    id: 12,
    documentId: "a12",
    title: "Shoprite Group extends 2026 bursary intake as applications open",
    slug: "shoprite-group-extends-2026-bursary",
    excerpt: "BUSINESS NEWS - The Shoprite Group has opened applications for its 2026 bursary programme, offering financial support and a guaranteed pathway into employment.",
    isTopStory: false,
    isBreaking: false,
    isFeatured: false,
    viewCount: 280,
    publishedDate: "2026-02-05T12:00:00.000Z",
    section: "business",
    createdAt: "2026-02-05T12:00:00.000Z",
    updatedAt: "2026-02-05T12:00:00.000Z",
    category: { id: 4, name: "Business", slug: "business", color: "#DC2626", parentSection: "news" },
    author: { id: 3, name: "Business Desk", slug: "business-desk", role: "Editor" },
  },
  {
    id: 13,
    documentId: "a13",
    title: "Gesin beseer toe trok in huis inploeg",
    slug: "gesin-beseer-toe-trok-in-huis-inploeg",
    excerpt: "GEORGE NUUS - 'n Gesin is beseer toe 'n trok Saterdagoggend in hul huis ingeploeg het. Die voorval het groot skade en beserings veroorsaak.",
    isTopStory: false,
    isBreaking: false,
    isFeatured: false,
    viewCount: 4200,
    publishedDate: "2026-02-01T12:00:00.000Z",
    section: "local",
    createdAt: "2026-02-01T12:00:00.000Z",
    updatedAt: "2026-02-01T12:00:00.000Z",
    category: { id: 3, name: "Local News", slug: "local-news", color: "#DC2626", parentSection: "news" },
    author: { id: 1, name: "George Herald Reporter", slug: "george-herald-reporter", role: "Journalist" },
  },
  {
    id: 14,
    documentId: "a14",
    title: "Untreated depression can endanger both mother and baby",
    slug: "untreated-depression-can-endanger",
    excerpt: "LIFESTYLE NEWS - Pregnancy is often expected to be a joyful time, yet for many women it is filled with fear, sadness, anxiety or emotional distress.",
    isTopStory: false,
    isBreaking: false,
    isFeatured: false,
    viewCount: 620,
    publishedDate: "2026-02-03T12:00:00.000Z",
    section: "lifestyle",
    createdAt: "2026-02-03T12:00:00.000Z",
    updatedAt: "2026-02-03T12:00:00.000Z",
    category: { id: 5, name: "Lifestyle", slug: "lifestyle", color: "#DC2626", parentSection: "lifestyle" },
    author: { id: 1, name: "George Herald Reporter", slug: "george-herald-reporter", role: "Journalist" },
  },
];

export const mockVideos: Video[] = [
  {
    id: 1,
    documentId: "v1",
    title: "Hat-Tricks & Humiliation! Pacaltsdorp United crush George | Behind The Wickets",
    slug: "hat-tricks-humiliation-pacaltsdorp-united",
    description: "Watch highlights from the dramatic cricket match between Pacaltsdorp United and George.",
    videoUrl: "https://www.youtube.com/watch?v=example1",
    duration: "12:34",
    section: "sport",
    publishedDate: "2026-02-06T10:00:00.000Z",
    viewCount: 1500,
  },
  {
    id: 2,
    documentId: "v2",
    title: "Forest squatting sparks concern in George | Neighbourhood Watch Patrol discovery",
    slug: "forest-squatting-sparks-concern",
    description: "A Neighbourhood Watch patrol has discovered illegal squatting in George's forests.",
    videoUrl: "https://www.youtube.com/watch?v=example2",
    duration: "8:21",
    section: "news",
    publishedDate: "2026-02-05T10:00:00.000Z",
    viewCount: 2300,
  },
  {
    id: 3,
    documentId: "v3",
    title: "Badgers under pressure as club cricket and schools SA20 take centre stage",
    slug: "badgers-under-pressure-cricket",
    description: "Cricket coverage focusing on the Badgers' challenging season.",
    videoUrl: "https://www.youtube.com/watch?v=example3",
    duration: "15:07",
    section: "sport",
    publishedDate: "2026-01-23T12:00:00.000Z",
    viewCount: 980,
  },
  {
    id: 4,
    documentId: "v4",
    title: "VIDEO: Badgers Under Pressure, Club Cricket Heats Up & SA U/19 Breakthroughs Shine",
    slug: "badgers-under-pressure-club-cricket",
    description: "Weekly cricket roundup with exciting local developments.",
    videoUrl: "https://www.youtube.com/watch?v=example4",
    duration: "18:42",
    section: "sport",
    publishedDate: "2026-01-16T10:00:00.000Z",
    viewCount: 750,
  },
];

export const mockGalleries: Gallery[] = [
  {
    id: 1,
    documentId: "g1",
    title: "Langkloof storm wreaks havoc",
    slug: "langkloof-storm-wreaks-havoc",
    description: "Photos from the devastating storm that struck the Langkloof area.",
    section: "general",
    publishedDate: "2026-02-06T10:00:00.000Z",
  },
  {
    id: 2,
    documentId: "g2",
    title: "Screaming for justice",
    slug: "screaming-for-justice",
    description: "Community members gather to demand justice in George.",
    section: "general",
    publishedDate: "2026-02-05T10:00:00.000Z",
  },
  {
    id: 3,
    documentId: "g3",
    title: "Hart-LOOP-byeenkoms sorg vir goeie atletiek",
    slug: "hart-loop-byeenkoms-atletiek",
    description: "Athletic event showcases local school talent.",
    section: "schools",
    publishedDate: "2026-02-05T09:00:00.000Z",
  },
  {
    id: 4,
    documentId: "g4",
    title: "2026 first-year students welcomed at NMU",
    slug: "2026-first-year-students-nmu",
    description: "NMU George campus welcomes its new class of 2026.",
    section: "special-events",
    publishedDate: "2026-02-04T08:00:00.000Z",
  },
];

export const mostReadArticles: Article[] = mockArticles
  .sort((a, b) => b.viewCount - a.viewCount)
  .slice(0, 10);
